-- Add ui_spec column to messages table for storing C1 UI specifications
ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS ui_spec JSONB;

-- Add comment to document the column
COMMENT ON COLUMN public.messages.ui_spec IS 'Stores UI specifications generated by Thesys C1 API';