// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egqbvpsasbmxcmwzxizv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVncWJ2cHNhc2JteGNtd3p4aXp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTY3OTYsImV4cCI6MjA3MDc3Mjc5Nn0.Lz0rHRgQX1nSJofvjQ_gjYhF8c8XgbVrg2GO7zvu2s8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});